import Head from "next/head";
import Image from "next/image";
import Footer from "@/component/Footer";
import styles from "@/styles/Home.module.css";
import HeroBanner from "@/component/HeroBanner";
import HighlightSection from "@/component/HighlightSection";
import CatergorySection from "@/component/CatergorySection";
import { useEffect } from "react";
import axios from "axios";

export default function Home(props) {
  useEffect(() => {
    console.log("props", props);
  }, [props]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroBanner />
        <HighlightSection highlights={props.highlights} />
        <CatergorySection categories={props.categories} />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  let props = { highlights: [], categories: [] };

  await axios
    .get(`https://web-dev.dev.kimo.ai/v1/highlights`)
    .then(async (response) => {
      props.highlights = response.data;
    })
    .catch((error) => {
      highlights = ["Error"];
      console.log("Error Highlights  :/highlights", { ...error });
    });

  await axios
    .get(`https://web-dev.dev.kimo.ai/v1/categories`)
    .then(async (response) => {
      props.categories = response.data;
    })
    .catch((error) => {
      props.categories = ["Error"];
      console.log("Error categories  : /categories", { ...error });
    });

  return { props };
}
